# Site settings
author: T Shipley
title: Code Becomes More Than Fun
header-img: img/home-bg.png
email: taneymail@gmail.com
copyright_name: T Shipley
description: > # this means to ignore newlines until "baseurl:"
  My Programming Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  taneymail

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
